# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: ./mvnw -Pprod clean package -DskipTests
    - name: Build image
      run: docker build -t demo-admin:$NOW .
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log in to DO Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Tag image
      run:
        docker tag demo-admin:$NOW registry.digitalocean.com/luffy-container-registry/demo-admin:$NOW
    - name: Push image to DO Container Registry
      run: docker push registry.digitalocean.com/luffy-container-registry/demo-admin:$NOW
    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.KEY}}
        script: |
          docker pull registry.digitalocean.com/luffy-container-registry/demo-admin:$NOW
          docker run --add-host host.docker.internal:host-gateway -p 8081:8081 -e _JAVA_OPTIONS=-Xmx512m -Xms256m -e SPRING_PROFILES_ACTIVE=prod,api-docs -e MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true -e EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka -e JHIPSTER_SLEEP=30 -e SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/demo_admin -e JDBC_DATABASE_USERNAME=keycloak -e JDBC_DATABASE_PASSWORD=123456 -e OIDC_URL=https://account.leequyt.monster/auth/realms/jhipster -e OIDC_CLIENT_ID=web_app -e OIDC_CLIENT_SECRET=web_app demo-admin:$NOW
